In [1]:
#NumPy

In [2]:
import numpy as np

In [3]:
my_list = [1,2,3]
my_array = np.array([1,2,3])

In [4]:
type(my_list)

list

# Creating NumPy array from Objects


type(my_array)

In [6]:
my_list

[1, 2, 3]

In [7]:
np.array(my_list)

array([1, 2, 3])

In [9]:
my_matrix=([1,2,3],[4,5,6],[7,8,9])

In [10]:
my_matrix

([1, 2, 3], [4, 5, 6], [7, 8, 9])

In [11]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Built-in Methods to create arrays

In [14]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.arange(0,100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [17]:
np.arange(0,100,5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [19]:
np.zeros((1,1))

array([[0.]])

In [20]:
np.zeros((1,2))

array([[0., 0.]])

In [21]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [22]:
np.linspace(0,5,20)

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

In [23]:
np.linspace(0,10,2)

array([ 0., 10.])

In [24]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [25]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [27]:
np.random.rand(2)

array([0.11171069, 0.15507419])

In [28]:
np.random.randint(1,100)

29

In [29]:
np.random.randint(1,100,10)

array([85,  6, 17, 31, 10, 18, 57, 48, 16, 89])

In [31]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [32]:
np.random.seed(42)
np.random.rand(5)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864])

In [33]:
np.random.seed(41)
np.random.rand(4)

array([0.25092362, 0.04609582, 0.67681624, 0.04346949])

In [34]:
np.random.seed(41)
np.random.rand(4)

array([0.25092362, 0.04609582, 0.67681624, 0.04346949])

In [35]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [36]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

# Array Attributes and Methods

In [37]:
arr=np.arange(0,10)

In [38]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
ranarr=np.random.rand(10)

In [46]:
ranarr

array([5.64115790e-02, 7.21998772e-01, 9.38552709e-01, 7.78765841e-04,
       9.92211559e-01, 6.17481510e-01, 6.11653160e-01, 7.06630522e-03,
       2.30624250e-02, 5.24774660e-01])

In [43]:
ranarr1=np.random.randint(0,10)

In [44]:
ranarr1

5

In [49]:
arr.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [50]:
arr.reshape(2,2) # error

ValueError: cannot reshape array of size 10 into shape (2,2)

# max, min, argmax, argmin


In [51]:
ranarr

array([5.64115790e-02, 7.21998772e-01, 9.38552709e-01, 7.78765841e-04,
       9.92211559e-01, 6.17481510e-01, 6.11653160e-01, 7.06630522e-03,
       2.30624250e-02, 5.24774660e-01])

In [52]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
arr.max

<function ndarray.max>

In [54]:
arr.max()

9

In [55]:
arr.min()

0

In [56]:
arr.argmax()

9

In [57]:
ranarr.max()

0.9922115592912175

In [58]:
ranarr.argmax()

4

# NumPy Indexing and Selection

In [61]:
arr = np.arange(0,11)

In [62]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [66]:
##Get a value at an index
arr[10]

10

In [64]:
arr[1:3]

array([1, 2])

In [65]:
arr[3:8]

array([3, 4, 5, 6, 7])

# Broadcasting

In [67]:
#Setting a value with index range (Broadcasting)
arr[0:5]=100

#Show
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [68]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [70]:
# Reset array
arr = np.arange(0,11)

#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [71]:
slice_of_arr=arr[0:6]

In [72]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [73]:
slice_of_arr[:]=99

In [74]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [75]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

# Indexing a 2D array (matrices)

In [76]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

In [77]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [78]:
arr_2d[2]

array([35, 40, 45])

In [79]:
arr_2d[1]

array([20, 25, 30])

In [80]:
#Shape (2,2) from top right corner
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

# Conditional Selection


In [81]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [82]:
arr>2

array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True])

In [83]:
arr>9

array([False, False, False, False, False, False, False, False, False,
        True])

In [84]:
bool_arr=arr>9

In [85]:
arr[bool_arr]

array([10])

In [86]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [87]:
arr[arr>8]

array([ 9, 10])

In [90]:
x=3
arr[arr>x]

array([ 4,  5,  6,  7,  8,  9, 10])

In [91]:
arr[arr<x]

array([1, 2])